### ISSUE TITLE
Print Bike Map

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-geospatial#73]
## Description
The City of Austin publishes a print version of the bike map every year. The bike map shows the recommended routes for bicycling, and it displays them by level of comfort so that they may be useful for people of all ages and abilities. The bike map is a collaboration between Active Transportation & Street Design, Public Information Office and the Data & Technology Services Team at Austin Transportation Department.

### Resources

[cityofaustin/atd-geospatial/issues/73](https://github.com/cityofaustin/atd-geospatial/issues/73)
[Mapping Comfort](https://peopleforbikes.org/blog/mapping-comfort-how-psychological-stress-influences-bike-maps/)
[Four Types of Cyclists](https://www.portlandoregon.gov/transportation/44597?a=237507)

**Comment by alan-deanda** [comment]
• Learned that many new subdivisions and streets are missing from bike map (last GIS import seems to be mine from 2014).
• Started querying data to import new streets and created templates for import into AI
• Refine streets template for import into AI - it doesn't align perfectly well despite following scale levels and document size conventions found in bike map folder in G Drive.
• Simplify street geometry once in AI
• Update missing streets
• Work on simpler symbology to potentially combine stroke and shadow into single line. The fact that they are split into separate geometries causes several issues:
    1. The map is hard to work on due to all the overlapping lines (especially for new people)
    2. We end up with duplicate geometries that make the map messy
    3. The map loads more slowly

__Sophia Benner may need to leave project to focus on other work, and I may need to update the front of the map as well the as the back.__

**Comment by alan-deanda** [comment]
### _Updates:_ ###
* Still working on basemap issues
* Sophia Benner will concentrate on infographics, and I will continue to update the map itself
### Upcoming tasks: ###

- [ ] Finish updating missing streets and labels
- [ ] Define symbology for trails on which dockless mobility devices are not allowed on
- [ ] Simplify document (this will be a long task that may need to happen post  current update)

**Comment by johnclary** [comment]
@alan-deanda i added the `Index` label to this project. would you update the description to match our project template?

**Comment by alan-deanda** [comment]
@johnclary I've updated the description to match the project template. Would it be more to spec to create a Project Index issue in the atd-datatech repo that cites this issue (currently in geospatial) as a reference?

**Comment by johnclary** [comment]
@alan-deanda good catch. Yes, please do exactly that!
